version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: bola9_postgres
    restart: always
    environment:
      POSTGRES_USER: bola9_admin
      POSTGRES_PASSWORD: bola9_password_segura
      POSTGRES_DB: bola9_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - bola9_data:/var/lib/postgresql/data
    networks:
      - bola9_network

  backend:
    build: .
    container_name: bola9_backend
    restart: always
    depends_on:
      - postgres_db
    env_file:
      - .env
    networks:
      - bola9_network
    volumes:
      - bola9_uploads:/app/uploads

  frontend:
    build: ./bola9-frontend
    container_name: bola9_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3003:80"
    networks:
      - bola9_network

volumes:
  bola9_data:
  bola9_uploads:

networks:
  bola9_network:
